---
infinispan:
  cluster:
    mode: server # (cluster|server): Choose cluster if you > 1 server, server if you have a single server
    initialServer: localhost # Has to be overridden on start
    name: Kamehameha

  cache:
    enabled: false
    maxEntries: 50000

  remote:
    primaryCacheName: main
    primaryCompression: com.zalora.aloha.compressor.Lz4

    secondaryCacheName: session
    secondaryCompression:

memcached:
  host: 0.0.0.0
  idleTime: 2000
  verbose: false
  port:
    primary : 11211
    secondary: 11212

server.port: 8080
logging.level.root: INFO
management.security.enabled: false
endpoints.shutdown.enabled: true
