---
infinispan:
  cluster:
    mode: server # (cluster|server): Choose cluster if you > 1 server, server if you have a single server
    initialServer: localhost # Has to be overridden on start
    name: Kamehameha

  cache:
    enabled: false
    maxEntries: 50000

  remote:
    cacheName: memcachedCache
    compression: #com.zalora.aloha.compressor.Lz4

memcached:
  host: 0.0.0.0
  idleTime: 2000
  verbose: false
  port: 11211

logging.level.root: INFO
